name:                hs
version:             0.1.0.0
github:              "kirchnergo/pfad/hs"
license:             BSD3
author:              "Göran Kirchner"
maintainer:          "goeran.kirchner@gmx.de"
copyright:           "Copyright (c) 2018-2019 Göran Kirchner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Algorithms, Functional Programming

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kirchnergo/pfad/hs#readme>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs

tests:
  hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
    - hspec

benchmarks:
  hs-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
    - criterion
